// <auto-generated />
using Alıştırma.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alıştırma.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Alıştırma.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            Title = "Title 1 *Seed"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            Title = "Title 2 *Seed"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            Title = "Title 3 *Seed"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description 4",
                            Title = "Title 4 *Seed"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description 5",
                            Title = "Title 5 *Seed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
